server:
  port: 9191
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost

resilience4j.circuitbreaker:
    instances:
        order-service:
            registerHealthIndicator: true
            slidingWindowSize: 100
        payment-service:
            registerHealthIndicator: true
            slidingWindowSize: 10
 